/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-19 12:18:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t<!-- <link rel=\"stylesheet\" href=\"../../resources/css/bootstrap.css\"> ../안하고 하면 적용안됨 \r\n");
      out.write(" -->\t<title>회원가입</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"../../resources/css/custom.css\"> <!--../안하고 하면 적용안됨  -->\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"resources/js/bootstrap.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css\" integrity=\"sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M\" crossorigin=\"anonymous\">\r\n");
      out.write("\t<!--다운받고 경로지정해주기 -->\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\"> <!-- 반응형 고정폭 콘테이너 -->\r\n");
      out.write("\t\t<form method=\"post\" action=\"/travelduo/minsert\">\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-hover\" style=\"text-align: center; border: 1px solid #dddddd\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th colspan=\"3\"><h4>회원 등록 양식 </h4></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width:110px; \"><h5>아이디</h5>\r\n");
      out.write("\t\t\t\t\t\t<td><input  class=\"form-control\" type=\"text\" id=userID\" name=\"userID\" maxLength=\"20\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width: 110px;\"><buttom class=\"btn btn-primary\" onclick=\"registerCheckFunction();\" type=\"button\">중복체크</buttom></td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width:110px; \"><h5>비밀번호</h5>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"form-control\" type=\"password\" id=userPassword1\" name=\"userPassword1\" maxLength=\"20\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width:110px; \"><h5>비밀번호 확인</h5>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"form-control\" type=\"password\" id=userPassword2\" name=\"userPassword2\" maxLength=\"20\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width:110px; \"><h5>이름</h5>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"form-control\" type=\"text\" id=username\" name=\"username\" maxLength=\"20\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width:110px; \"><h5>나이</h5>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"form-control\" type=\"text\" id=userAge\" name=\"userAge\" maxLength=\"20\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width:110px; \"><h5>성별</h5></td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group\" style=\"text-align: center; margin: 0 auto;\">\r\n");
      out.write("\t\t\t\t\t<!--버튼그룹으로 감쌀 수 있도록 바꾸기  --> <div class=\"btn-group\" data-toggle=buttons\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t \t\t<label class=\"btn btn-primary active\">\r\n");
      out.write("\t\t\t\t\t\t\t \t\t\t<input type=\"radio\" name=\"userGender\" autocomplete=\"off\" value=\"남자\" checked>남자 \r\n");
      out.write("\t\t\t\t\t\t\t \t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t \t<label class=\"btn btn-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t<input type=\"radio\" name=\"userGender\" autocomplete=\"off\" value=\"여자\">여자\r\n");
      out.write("\t\t\t\t\t\t\t\t \t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"width:200px; \"><h5>이메일</h5></td>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\"><input class=\"form-control\" type=\"email\" id=\"userEmail\" name=\"userEmail\" maxLength=\"20\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<!--단 한개의 열만 들어갈 수 있도록 함.  -->\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: left\" colspan=\"3\"><input class=\"btn btn-outline-primary pull-right\" type=\"submit\" value=\"회원가입\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<td\tstyle=\"text-align: center\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-outline-danger\">작성취소</button>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t<!-- 부트스트랩에서 사용가능한 class 를 통해 여러가지 특성을 넣어줄 수 있다. -->\r\n");
      out.write("\t\t\t\t\t<!-- 클래스에 btn 을 쓰면 , 부트스트랩이 적용되고 , 그 뒤에 btn-primary 는 파란색 , btn-success 는 초록색 , btn-warning 은 주황색 btn-info 는 푸른색 ,btn-danger 는 빨간색을 의미한다. -->\r\n");
      out.write("\t\t\t\t\t<!-- btn btn-primary 이후 pull-right 를쓰면 맨 오른쪽으로 이동한다 . 근데 pull-left , pull-center는 안되네  -->\r\n");
      out.write("\t\t\t\t\t<!-- btn-lg는 커지게하는거, btn-sm 작게, btn-xs 는 더 작게 인데 서로간의 중복은 허용되는 거 같으면서도 안되는거같고 그러네 -->\r\n");
      out.write("\t\t\t\t\t<!--  물론 버튼뿐아니라 글씨에도 적용가능하다.-->\r\n");
      out.write("\t\t\t\t\t<!--그리고 class=btn-primary 이랑 class=\"btn btn-primary\" 가 다르다  선자가 그림자가 지고 후자가 그림자가 없네...알아두기 -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- text-align은  글의 어떤곳에 위치할지를 말해주는 애. -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- class=\"form-control\" 은 너비 100짜리를 주는애 -->\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
