/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-04-01 08:32:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import board_hoogi.model.vo.*;
import java.util.*;
import board_hoogi.model.vo.Product_Hoogi;
import member.model.vo.Member;
import member.model.vo.Member;

public final class hoogiListView3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/board/../common/header.jsp", Long.valueOf(1554103031221L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("board_hoogi.model.vo");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("board_hoogi.model.vo.Product_Hoogi");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("     \r\n");

	ArrayList<Product_Hoogi> list = 
			(ArrayList<Product_Hoogi>)request.getAttribute("list");
	
	int listCount = ((Integer)request.getAttribute("listCount")).intValue();
	int startPage = ((Integer)request.getAttribute("startPage")).intValue();
	int endPage = ((Integer)request.getAttribute("endPage")).intValue();
	int maxPage = ((Integer)request.getAttribute("maxPage")).intValue();
	int currentPage = ((Integer)request.getAttribute("currentPage")).intValue();

	
	String type = null; 
	String word = null;
	//java.sql.Date begin = null, end = null;
	
	if(request.getAttribute("type") != null){
		type = request.getAttribute("type").toString();	
		word = request.getAttribute("word").toString();
	}
	
	//Member loginUser = (Member)session.getAttribute("loginUser");
	
	

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write(" <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function moveWritePage(){\r\n");
      out.write("\tlocation.href=\"/travelduo/views/board/hoogiWriterForm.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function message(){\r\n");
      out.write("\tvar toUser = $(\"#message2\").val();\r\n");
      out.write("\tvar url =\"/travelduo/views/message/message.jsp?id=\"+toUser;\r\n");
      out.write("\twindow.open(url, \"\", \"width=400, height=400, left=600\");\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function message3(){\r\n");
      out.write("\tvar toUser = $(\"#message3\").val();\r\n");
      out.write("\tlocation.href=\"/travelduo/views/message/message.jsp?id=\"+toUser;\r\n");
      out.write("\twindow.open(url, \"\", \"width=400, height=400, left=600\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function winOpen(){\r\n");
      out.write("\tvar url =\"/travelduo/views/message/message.jsp\";\r\n");
      out.write("window.open(url ,\"new\",\"width=500,height=500,top=100,left=100\"); \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <style>\r\n");
      out.write("  table, th, td {\r\n");
      out.write("    border: 1px solid #bcbcbc;\r\n");
      out.write("  }\r\n");
      out.write("  table {\r\n");
      out.write("    width: 50%;\r\n");
      out.write("    height: 70px;\r\n");
      out.write("  }\r\n");
      out.write("  </style>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"/travelduo/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");


      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>travelduo</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function openNav() {\r\n");
      out.write("\t  document.getElementById(\"mySidenav\").style.width = \"257px\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction closeNav() {\r\n");
      out.write("\t  document.getElementById(\"mySidenav\").style.width = \"0\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".sidenav {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 0;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  background-color: #111;\r\n");
      out.write("  overflow-x: hidden;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("  padding-top: 60px;\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" /* 회원가입 , ID/PW 찾기 */\r\n");
      out.write(".sidenav a {\r\n");
      out.write("  padding: 8px 8px 8px 9px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("  color: #818181;\r\n");
      out.write("  display: block;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav a:hover {\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav .closebtn {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 23px;\r\n");
      out.write("  font-size: 36px;\r\n");
      out.write("  margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-height: 6000px) {\r\n");
      out.write("  .sidenav {padding-top: 15xp;}\r\n");
      out.write("  .sidenav a {font-size: 18px;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 여행가듀오 로고아래 로그인에 대한 글씨 */\r\n");
      out.write(" .logincolor818181 { \r\n");
      out.write(" color: #818181;\r\n");
      out.write(" } \r\n");
      out.write(" \r\n");
      out.write("/*로그인 글자 앞에 생기는 줄에대한 것  */\r\n");
      out.write(".logincolor818181:after {display: inline-block; margin: 0 0 6px 5px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:\r\n");
      out.write("44%; }\r\n");
      out.write("\r\n");
      out.write("/*로그인버튼  앞에 생기는 줄에 대한 것  */\r\n");
      out.write(".line:before {display: inline-block; margin: 0 5px 6px 23px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:\r\n");
      out.write("38%; }\r\n");
      out.write("\r\n");
      out.write("/*로그인 후 햄버거 클릭 시 나오는 앞선에 대한 것  */\r\n");
      out.write(".line2:before {display: inline-block; margin: 0 5px 6px 23px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:83%;}\r\n");
      out.write("\r\n");
      out.write("/*로그인 후 햄버거 클릭 시 나오는 뒷선에 대한 것  */\r\n");
      out.write(".line3:before {display: inline-block; margin: 0 5px 6px 23px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:\r\n");
      out.write("83%;}\r\n");
      out.write("\r\n");
      out.write("/* \r\n");
      out.write("\t\t\tCSS\r\n");
      out.write("\t\t\t============================================= -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/linearicons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/travelduo/resources/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/animate.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.min.css\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"main\">\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"container main-menu\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-center justify-content-between d-flex\">\r\n");
      out.write("\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/travelduo/index.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/travelduo/resources/images/logo2.png\" alt=\"\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"height: 30px;\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<nav id=\"nav-menu-container\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/milist\">매칭시스템</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/views/product/productListView.jsp\">국내여행</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/palist\">해외여행\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=일본\">일본</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pdlist?des=오사카\">오사카</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist\">후쿠오카</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">야마가타 현</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist\">홍콩</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">방콕</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">대만</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=미국\">미국</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">파리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">도쿄</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/views/admin/dashBoard.jsp\">발리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"hotels.html\">테마여행</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/blist\">매칭게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 if(loginUser!=null) { 
      out.write("\r\n");
      out.write("\t\t<li><a href=\"/travelduo/matchList?userid=");
      out.print( loginUser.getUserId() );
      out.write("\"> 내게 온 매칭</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 }else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/travelduo/views/admin/dashBoard.jsp\">여행후기</a>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/nlist?page=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/views/faq/faq.jsp\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/qlist?page=1\">QnA</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"font-size:15px;color:white;cursor:pointer\" onclick=\"openNav()\">&#9776;　</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- #nav-menu-container -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"mySidenav\" class=\"sidenav\">\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\r\n");
      out.write("  <a href=\"/travelduo\" align=\"center\"><img src=\"/travelduo/resources/images/logo2.png\" width= \"180\" height= \"60\"></a><br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
if(loginUser!=null){ 
      out.write("<!--로그인하였을 경우  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<p class=\"line2\"></p>\r\n");
      out.write("<ul class=\"fa-ul\">\r\n");
      out.write("\r\n");
      out.write("<a href=\"/travelduo/views/member/memberMyPage.jsp\" > <img src=\"/travelduo/resources/images/Person_icon-icons.com_51960.png\" width= \"20\" height= \"20\"> 회원정보 보기/수정</a>\r\n");
      out.write("<a href=\"/travelduo/views/member/memberDibs.jsp\" > <img src=\"/travelduo/resources/images/Gift_icon-icons.com_52072.png\" width= \"20\" height= \"20\"> 찜한상품</a>\r\n");
      out.write("<a href=\"/travelduo/views/member/memberPay.jsp\" > <img src=\"/travelduo/resources/images/Money-bag-euro_icon-icons.com_51997.png\" width= \"20\" height= \"20\"> 결제 내역 확인</a>\r\n");
      out.write("<a href=\"\" > <img src=\"/travelduo/resources/images/Phone-call_icon-icons.com_51956.png\" width= \"20\" height= \"20\"> 고객 센터 문의</a>\r\n");
      out.write("<a href=\"/travelduo/logout\" > <img src=\"/travelduo/resources/images/Login_icon-icons.com_52028 (1).png\" width= \"20\" height= \"20\"> 로그아웃</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("<p class=\"line3\"></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t<!-- \t <ul class=\"fa-ul\">\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span><a href=\"\"><h5>회원정보 확인/수정</h5></a></li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>찜한 상품</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>결제 내역 확인</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>고객센터</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <a href=\"/travelduo/logout\"><li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span></li>로그아웃</a>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("           </ul>  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
}else{ 
      out.write("<!--로그인하지 않았을 경우  -->\r\n");
      out.write("<form action=\"/travelduo/login\" method=\"post\">\r\n");
      out.write(" \r\n");
      out.write("  <h4 class=\"logincolor818181\">&ensp;&ensp; 로그인</h4> \r\n");
      out.write("\r\n");
      out.write("<div style = \"padding: 4px 1px 3px 3px;\">  \r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>&ensp;&emsp;<input type=\"text\" name=\"userid\" placeholder=\"ID\" required></td>\r\n");
      out.write("\t</tr><br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style = \"padding: 4px 1px 10px 3px;\"> \r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>&ensp;&emsp;<input type=\"password\" name=\"userpwd\" placeholder=\"Password\" required></td><br>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("&ensp;&ensp;&emsp;<input type=\"checkbox\"  value=\"Y\" onclick=\"if(this.checked) return confirm('로그인 유지 기능을 사용할 경우! 브라우저를 닫더라도 로그인이 계속 유지될 수 있습니다.\\n\\n따라서 공공장소에서 이용 할 경우 반드시 로그아웃을 하시길 바랍니다.');\"><span style=\"color:#818181\">자동 로그인</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tr><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<tr>\r\n");
      out.write("&ensp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp;&ensp;&ensp;&ensp;<p class=\"line\"><input class=btn type=\"submit\" value=\"로 그 인\"></p>\r\n");
      out.write("</tr>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<div class=\"btn\">\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"/travelduo/views/member/memberAccept.jsp\">회원가입</a>\r\n");
      out.write("\t<a href=\"\">ID/PW 찾기</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</tr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 if(loginUser != null && loginUser.getUserId().equals("admin")){ 
      out.write("\r\n");
      out.write("\t<!--관리자 전용 페이지 만든후 거기로이동하게 끔  --> \t\r\n");
      out.write("\t<td><a href=\"/travelduo/views/admin/dashBoard.jsp\">관리자 페이지로 이동</a></td>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--   로그인화면 -->\r\n");
      out.write("<!--   <form>\r\n");
      out.write("                <div class=\"form-label-group\">\r\n");
      out.write("                  <input type=\"id\" id=\"inputId\" class=\"form-control\" placeholder=\"ID\" required autofocus>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-label-group\">\r\n");
      out.write("                  <input type=\"password\" id=\"inputPassword\" class=\"form-control\" placeholder=\"Password\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <button class=\"btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2\" type=\"submit\">로그인</button>\r\n");
      out.write("                \r\n");
      out.write("                <button class=\"btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2\" type=\"button\">아이디 비밀번호찾기</button>\r\n");
      out.write("                <button class=\"btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2\" type=\"button\">회원가입</button>\r\n");
      out.write("              </form> -->\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("<!-- 회원가입 -->\r\n");
      out.write("<!--               <article class=\"container\">\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("                <div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("                <h3><a href=\"#\">회원가입</a></h3>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-6 col-md-offset-3\">\r\n");
      out.write("                <form role=\"form\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputName\"><a href=\"#\">성명</a></label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"inputName\" placeholder=\"이름을 입력해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"InputEmail\"><a href=\"#\">이메일 주소</a></label>\r\n");
      out.write("                        <input type=\"email\" class=\"form-control\" id=\"InputEmail\" placeholder=\"이메일 주소를 입력해주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputPassword\"><a href=\"#\">비밀번호</a></label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"inputPassword\" placeholder=\"비밀번호를 입력해주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputPasswordCheck\"><a href=\"#\">비밀번호 확인</a></label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"inputPasswordCheck\" placeholder=\"비밀번호 확인을 위해 다시한번 입력 해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputMobile\"><a href=\"#\">휴대폰 번호</a></label>\r\n");
      out.write("                        <input type=\"tel\" class=\"form-control\" id=\"inputMobile\" placeholder=\"휴대폰번호를 입력해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputtelNO\"><a href=\"#\">비밀번호 힌트</a></label>\r\n");
      out.write("                        <select name=\"\">\r\n");
      out.write("                        <option value=\"좋아하는 색은?\" selected>좋아하는 색은?\r\n");
      out.write("                        <option value=\"아버지 성함은?\">아버지 성함은?\r\n");
      out.write("                        <option value=\"어머니 성함은?\">어머니 성함은?\r\n");
      out.write("                        <option value=\"첫번째 연인의 이름은?\">첫사랑 했던 연인의 이름은?\r\n");
      out.write("                        <option value=\"일생중 일어났던 중요한 사건은?\">일생중 일어났던 중요한 사건은?\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"hint\"><a href=\"#\">힌트의 정답</a></label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"inputHint\" placeholder=\"정답을 입력해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                    <label>약관 동의</label>\r\n");
      out.write("                    <div data-toggle=\"buttons\">\r\n");
      out.write("                    <label class=\"btn btn-primary active\">\r\n");
      out.write("                    <span class=\"fa fa-check\"></span>\r\n");
      out.write("                    <input id=\"agree\" type=\"checkbox\" autocomplete=\"off\" checked>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <a href=\"#\">이용약관</a>에 동의합니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <div class=\"form-group text-center\">\r\n");
      out.write("                        <button type=\"submit\" id=\"join-submit\" class=\"btn btn-primary\">\r\n");
      out.write("                            회원가입<i class=\"fa fa-check spaceLeft\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-warning\">\r\n");
      out.write("                            가입취소<i class=\"fa fa-times spaceLeft\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>text-muted\r\n");
      out.write("                    <br>\r\n");
      out.write("\r\n");
      out.write("        </article> -->\r\n");
      out.write("        <br><br>\r\n");
      out.write("<!-- 마이페이지 -->\r\n");
      out.write("<!-- #header -->\r\n");
      out.write("\t<!--\r\n");
      out.write("\t\tJS\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("\t\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<table align=\"center\" width=\"550\" cellspacing=\"0\" border=\"1\" class=\"table table-striped\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th>번호</th>\r\n");
      out.write("\t<th>제목</th>\r\n");
      out.write("\t<th>작성자</th>\r\n");
      out.write("\t<th>조회수</th>\r\n");
      out.write("\t<th>날짜</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
 
if (list!=null){ 
	
  for(int i=0; i<list.size(); i++) { 

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th align=\"center\"> ");
      out.print( list.get(i).getBoardnum() );
      out.write("</th>\r\n");
      out.write("\t <th align=\"center\"> \r\n");
      out.write("\t \r\n");
      out.write("\t ");
 if(loginUser !=null){ 
      out.write("\r\n");
      out.write("\t <strong>\r\n");
      out.write("\t <a href=\"/travelduo/bdetail?bnum=");
      out.print( list.get(i).getBoardnum() );
      out.write("&page=");
      out.print( currentPage );
      out.write("\"\r\n");
      out.write("\tclass=\"text-info\" >\r\n");
      out.write("\t");
      out.print( list.get(i).getBtitle() );
      out.write("</a> </strong>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<strong><small> <a class=\"text-danger\"> [");
      out.print( list.get(i).getCommentcount() );
      out.write("]</a></small> </strong>\r\n");
      out.write(" </th>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--  드롭다운 네비 -->\r\n");
      out.write("\t<td>\r\n");
      out.write("\t<ul class=\"nav nav-pills\">\r\n");
      out.write("\t<li class=\"dropdown active\">\r\n");
      out.write("\t<a class=\"dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t");
      out.print( list.get(i).getUserid() );
      out.write(" <span class=\"caret\"></span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t</li><br>\r\n");
      out.write("\t<a href=\"/travelduo/bsearch?type=writer&word=");
      out.print(list.get(i).getUserid() );
      out.write("\">아이디로 게시글 검색</li><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 드롭다운 내비 끝  -->\r\n");
      out.write("\t\r\n");
      out.write("\t<td align=\"center\"> ");
      out.print( list.get(i).getHoogireadcount() );
      out.write("</td>\r\n");
      out.write("\t<td align=\"center\"> ");
      out.print( list.get(i).getBoarddate() );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
 } 
      out.write('\r');
      out.write('\n');
      out.write('	');
  } 
      out.write('\r');
      out.write('\n');
      out.write('	');
 }else{ 
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td> 작성된 게시글 없음</td>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\t<tr>\r\n");
      out.write("        <td colspan=\"2\">\r\n");
      out.write("   <input align=\"center\" type=\"button\" class=\"btn btn-primary\" value=\"목록 \" onclick=\"\"/>\r\n");
      out.write("   <button onclick=\"moveWritePage();\" align=\"center\" type=\"button\" class=\"btn btn-primary\" value=\"글쓰기\">글등록</button>\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("        <form></form>\r\n");
      out.write("          </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            </center>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t <center>\r\n");
      out.write("    <br>\r\n");
      out.write("    \r\n");
      out.write("    <!--  검색폼 -->\r\n");
      out.write("    <div id=\"searchForm\">\r\n");
      out.write("        <FORM name='frm' method='GET' action=\"/travelduo/bsearch\" \r\n");
      out.write("        class=\"navbar-search pull-left\">\r\n");
      out.write("            <SELECT name='type' class=\"chosen-select\" tabindex=\"5\">\r\n");
      out.write("                <option value=\"title\">제목</option>\r\n");
      out.write("                <option value=\"content\">내용</option>\r\n");
      out.write("                <option value=\"tcmix\">제목+내용</option>\r\n");
      out.write("                <option value=\"writer\">글쓴이</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <input type=\"text\" class=\"search-query\" size=\"20\" name=\"word\"/>&nbsp;\r\n");
      out.write("            <input type=\"submit\" class=\"btn btn-secondary\" value=\"검색\"/>\r\n");
      out.write("        </form>    \r\n");
      out.write("    </div>\r\n");
      out.write("</div>   \r\n");
      out.write("\r\n");
      out.write("\t</center> \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
 if(currentPage <= 1){ 
      out.write("\r\n");
      out.write("\t[맨처음]&nbsp;\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/travelduo/blist?page=1\">[맨처음]</a>&nbsp;\r\n");
 } 
      out.write('\r');
      out.write('\n');
 if((currentPage - 10) < startPage && (currentPage - 10) > 1){ 
      out.write("\r\n");
      out.write("\t<a href=\"/travelduo/blist?page=");
      out.print( startPage - 10 );
      out.write("\">[prev]</a>\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t[prev]\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
 for(int p = startPage; p <= endPage; p++){ 
		if(p == currentPage){

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<font color=\"red\" size=\"4\"><b>[");
      out.print( p );
      out.write("]</b></font>\r\n");
      out.write("\t");
 }else{ if(word != null && word.equals("title")){
      out.write("\r\n");
      out.write("\t\t<a href=\"/travelduo/bsearch?word=");
      out.print( word );
      out.write("&page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t");
}else if(word != null && word.equals("writer")){ 
      out.write("\r\n");
      out.write("\t\t<a href=\"/travelduo/bsearc?word=");
      out.print( word );
      out.write("&page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
      out.write("\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/travelduo/blist?page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\r\n");
 }}} 
      out.write("&nbsp;\r\n");
      out.write("\r\n");
 if((currentPage + 10) > endPage && (currentPage + 10) < maxPage){ 
      out.write("\r\n");
      out.write("\t<a href=\"/travelduo/blist?page=");
      out.print( endPage + 10 );
      out.write("\">[next]</a>&nbsp;\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t[next]&nbsp;\r\n");
 } 
      out.write('\r');
      out.write('\n');
 if(currentPage >= maxPage){ 
      out.write("\r\n");
      out.write("\t[맨끝]\r\n");
 }else{ 
      out.write("\r\n");
      out.write("\t<a href=\"/travelduo/blist?page=");
      out.print( maxPage );
      out.write("\">[맨끝]</a>\r\n");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 //관리자일 때만 글쓰기 제공 처리
	
	if(loginUser != null){ 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\" integrity=\"sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
