/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-04-05 09:36:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1554456826902L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1554293034000L));
    _jspx_dependants.put("/views/common/floating.jsp", Long.valueOf(1554390118000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("      ");
 
   String result =(String)request.getAttribute("result");
   String loginResult = (String)request.getAttribute("loginResult");
   String insertResult = (String)request.getAttribute("insertResult");
   
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function fnMove(seq){\r\n");
      out.write("    var offset = $(\"#h\" + seq).offset();\r\n");
      out.write("    $('html, body').animate({scrollTop : offset.top}, 400);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.onload=function(){\r\n");
      out.write("\t   ");
 if(result !=null && result.equals("success")){ 
      out.write("\r\n");
      out.write("\t      alert(\"탈퇴가 정상적으로 진행되었습니다.\\n이용해주셔서 감사합니다.\");\r\n");
      out.write("\r\n");
      out.write("\t   ");
 }else if(result != null && result.equals("fail")){ 
      out.write("\r\n");
      out.write("\t      alert(\"탈퇴가 이루어지지않았습니다.\");\r\n");
      out.write("\t   ");
 }else if(loginResult != null && loginResult.equals("fail")){ 
      out.write("\r\n");
      out.write("\t      alert(\"로그인 실패! \\n회원정보가 없거나 일치하지 않습니다.\");\r\n");
      out.write("\t   ");
 }else if(insertResult != null && insertResult.equals("success")){ 
      out.write("\r\n");
      out.write("\t      alert(\"회원가입 성공! \\n로그인 해주세요.\")\r\n");
      out.write("\t   ");
 } 
      out.write("\r\n");
      out.write("\t   \r\n");
      out.write("\t   }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>travel duo</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    \r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>travelduo</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/main.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function openNav() {\r\n");
      out.write("\t  document.getElementById(\"mySidenav\").style.width = \"257px\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction closeNav() {\r\n");
      out.write("\t  document.getElementById(\"mySidenav\").style.width = \"0\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".sidenav {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 0;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  background-color: #111;\r\n");
      out.write("  overflow-x: hidden;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("  padding-top: 60px;\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" /* 회원가입 , ID/PW 찾기 */\r\n");
      out.write(".sidenav a {\r\n");
      out.write("  padding: 8px 8px 8px 9px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("  color: #818181;\r\n");
      out.write("  display: block;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav a:hover {\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav .closebtn {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 23px;\r\n");
      out.write("  font-size: 36px;\r\n");
      out.write("  margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-height: 6000px) {\r\n");
      out.write("  .sidenav {padding-top: 15xp;}\r\n");
      out.write("  .sidenav a {font-size: 18px;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 여행가듀오 로고아래 로그인에 대한 글씨 */\r\n");
      out.write(" .logincolor818181 { \r\n");
      out.write(" color: #818181;\r\n");
      out.write(" } \r\n");
      out.write(" \r\n");
      out.write("/*로그인 글자 앞에 생기는 줄에대한 것  */\r\n");
      out.write(".logincolor818181:after {display: inline-block; margin: 0 0 6px 5px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:\r\n");
      out.write("44%; }\r\n");
      out.write("\r\n");
      out.write("/*로그인버튼  앞에 생기는 줄에 대한 것  */\r\n");
      out.write(".line:before {display: inline-block; margin: 0 5px 6px 23px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:\r\n");
      out.write("38%; }\r\n");
      out.write("\r\n");
      out.write("/*로그인 후 햄버거 클릭 시 나오는 앞선에 대한 것  */\r\n");
      out.write(".line2:before {display: inline-block; margin: 0 5px 6px 23px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:83%;}\r\n");
      out.write("\r\n");
      out.write("/*로그인 후 햄버거 클릭 시 나오는 뒷선에 대한 것  */\r\n");
      out.write(".line3:before {display: inline-block; margin: 0 5px 6px 23px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:\r\n");
      out.write("83%;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"main\">\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"container main-menu\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-center justify-content-between d-flex\">\r\n");
      out.write("\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/travelduo/index.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/travelduo/resources/images/logo2.png\" alt=\"\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"height: 30px;\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<nav id=\"nav-menu-container\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/index2.jsp\">매칭시스템</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pialist\">국내여행</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/poalist\">해외여행\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=일본\">일본</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=영국\">영국</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=프랑스\">프랑스</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=체코\">체코</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=미국\">미국</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=이탈리아\">이탈리아</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=헝가리\">헝가리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=독일\">독일</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=중국\">중국</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=호주\">호주</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=태국\">태국</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/blist\">매칭게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 if(loginUser!=null) { 
      out.write("\r\n");
      out.write("\t\t<li><a href=\"/travelduo/matchList?userid=");
      out.print( loginUser.getUserId() );
      out.write("\"> 내게 온 매칭</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 }else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/nlist?page=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/views/faq/faq.jsp\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/qlist?page=1\">QnA</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a><span style=\"font-size:15px;color:white;cursor:pointer\" onclick=\"openNav()\">&#9776;　</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- #nav-menu-container -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"mySidenav\" class=\"sidenav\">\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\r\n");
      out.write("  <a href=\"/travelduo\" align=\"center\"><img src=\"/travelduo/resources/images/logo2.png\" width= \"180\" height= \"60\"></a><br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
if(loginUser!=null){ 
      out.write("<!--로그인하였을 경우  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<p class=\"line2\"></p>\r\n");
      out.write("<ul class=\"fa-ul\">\r\n");
      out.write("\r\n");
      out.write("<a href=\"/travelduo/views/member/memberMyPage.jsp\" > <img src=\"/travelduo/resources/images/Person_icon-icons.com_51960.png\" width= \"20\" height= \"20\"> 회원정보 보기/수정</a>\r\n");
      out.write("<a href=\"/travelduo/index2.jsp\" > <img src=\"/travelduo/resources/images/멤버 매칭시스템 로고.png\" width= \"20\" height= \"20\"> 매칭 시스템</a>\r\n");
      out.write("<a href=\"/travelduo/nlist?page=1\" > <img src=\"/travelduo/resources/images/Phone-call_icon-icons.com_51956.png\" width= \"20\" height= \"20\"> 고객 센터 문의</a>\r\n");
      out.write("<a href=\"/travelduo/logout\" > <img src=\"/travelduo/resources/images/Login_icon-icons.com_52028 (1).png\" width= \"20\" height= \"20\"> 로그아웃</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("<p class=\"line3\"></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
}else{ 
      out.write("<!--로그인하지 않았을 경우  -->\r\n");
      out.write("<form action=\"/travelduo/mlogin\" method=\"post\">\r\n");
      out.write(" \r\n");
      out.write("  <h4 class=\"logincolor818181\">&ensp;&ensp; 로그인</h4> \r\n");
      out.write("\r\n");
      out.write("<div style = \"padding: 4px 1px 3px 3px;\">  \r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>&ensp;&emsp;<input type=\"text\" name=\"userid\" placeholder=\"ID\" required></td>\r\n");
      out.write("\t</tr><br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style = \"padding: 4px 1px 10px 3px;\"> \r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>&ensp;&emsp;<input type=\"password\" name=\"userpwd\" placeholder=\"Password\" required></td><br>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<tr>\r\n");
      out.write("&ensp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp;&ensp;&ensp;&ensp;<p class=\"line\"><input class=\"btn btn-secondary btn\" type=\"submit\" value=\"로 그 인\"></p>\r\n");
      out.write("</tr>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<div class=\"btn\">\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"/travelduo/views/member/memberAccept.jsp\">회원가입</a>\r\n");
      out.write("\t<a href=\"/travelduo/views/member/memberFindId.jsp\">ID/PW 찾기</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</tr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 if(loginUser != null && loginUser.getUserId().equals("admin")){ 
      out.write("\r\n");
      out.write("\t<!--관리자 전용 페이지 만든후 거기로이동하게 끔  --> \t\r\n");
      out.write("\t<ul class=\"fa-ul\">\r\n");
      out.write("\t<a href=\"/travelduo/mm\">관리자 페이지로 이동</a>\r\n");
      out.write("\t</ul>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t   <script type=\"text/javascript\" src=\"/travelduo/resources/js/superfish.min.js\"></script>\r\n");
      out.write("   <script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("   <script type=\"text/javascript\" src=\"/travelduo/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("   <script type=\"text/javascript\" src=\"/travelduo/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <header>\r\n");
      out.write("  <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>\r\n");
      out.write("    </ol>\r\n");
      out.write("    <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("      <!-- Slide One - Set the background image for this slide in the line below -->\r\n");
      out.write("      <div class=\"carousel-item active\" style=\"background-image: url('/travelduo/resources/images/japan1.jpg')\">\r\n");
      out.write("        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("          <h3 class=\"display-4\"><!-- 첫번째 사진 타이틀 --></h3>\r\n");
      out.write("          <p class=\"lead\"><!-- 첫번째 사진 내용 --></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Slide Two - Set the background image for this slide in the line below -->\r\n");
      out.write("      <div class=\"carousel-item\" style=\"background-image: url('/travelduo/resources/images/japan4.jpg')\">\r\n");
      out.write("        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("          <h3 class=\"display-4\"><!-- 두번째 사진 타이틀 --></h3>\r\n");
      out.write("          <p class=\"lead\"><!-- 두번째 사진 내용 --></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Slide Three - Set the background image for this slide in the line below -->\r\n");
      out.write("      <div class=\"carousel-item\" style=\"background-image: url('/travelduo/resources/images/japan3.jpg')\">\r\n");
      out.write("        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("          <h3 class=\"display-4\"></h3>\r\n");
      out.write("          <p class=\"lead\"></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("          <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Previous</span>\r\n");
      out.write("        </a>\r\n");
      out.write("    <a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("          <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("          <span class=\"sr-only\">Next</span>\r\n");
      out.write("        </a>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" class=\"bg-dark\">\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <!-- Portfolio Section -->\r\n");
      out.write("   <h2 class=\"text-center wow fadeIn\"></h2>\r\n");
      out.write("   <br><br>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("          <a href=\"/travelduo/pdetail?num=frspr\"><img class=\"card-img-top\" src=\"/travelduo/resources/images/paris.jpg\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"/travelduo/pdetail?num=frspr\">파리</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">파리는 프랑스의 수도이자 유럽의 대표도시 중 하나입니다. 파리와 같은 대도시는 짧은 일정으로는 둘러보기 힘들 정도로 관광명소가 많은데요. 따라서 서유럽 3개국 정도를 10박에 걸쳐 방문할 예정이라면, 파리에서 3박4일 정도는 머물러야 좋습니다. 프랑스는 미식가들의 나라인 만큼, 반드시 먹어봐야 할 것들도 소개해드립니다 :-)</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("           <a href=\"/travelduo/pdetail?num=ukld01\"><img class=\"card-img-top\" src=\"/travelduo/resources/images/london.jpg\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"/travelduo/pdetail?num=ukld01\">런던</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">영국의 수도인 런던은 세계 중요한 비지니스와 금융 도시의 하나일 뿐만 아니라, 세계의 정치, 교육, 엔터테인먼트, 대중문화, 패션에도 많은 영향을 끼치는 중요한 도시입니다. 런던은 또한 최고의 대규모 교통시설을 갖춘 도시중의 하나이기도 합니다. \r\n");
      out.write("런던에는 셀수없을 만큼의 많은 행사들과 볼거리들이 가득한 도시이며, 그중에 몇가지 아래의 볼거리들은 런던에 오면 꼭 봐야할 것들중에 속합니다.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("            <a href=\"/travelduo/pdetail?num=ukld01\"><img class=\"card-img-top\" src=\"/travelduo/resources/images/rome.jpg\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"/travelduo/pdetail?num=ukld01\">로마</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">로마는 고대의 유물, 유적이 많아 그것들을 훼손하지 않으려는 노력의 결과로 지하철이 발달되어 있지 않습니다. 따라서 로마는 대개 버스나 도보로 여행하게 되므로 편한 신발은 필수입니다. 서유럽을 방문한다면, 로마는 반드시 방문하길 추천합니다.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("           <a href=\"/travelduo/pdetail?num=sdn01\"><img class=\"card-img-top\" src=\"/travelduo/resources/images/sydney.jpg\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"/travelduo/pdetail?num=sdn01\">시드니</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">시드니는 세계에서 가장 활기찬 도시 중 하나이며, \r\n");
      out.write("호주의 다른 지역으로 여행하기 위한 관문이기도 합니다. 시드니는 다채롭고 활기찬 곳입니다.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("      <a href=\"/travelduo/pdetail?num=jposk02\"><img class=\"card-img-top\" src=\"/travelduo/resources/images/osaka.jpg\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"/travelduo/pdetail?num=jposk02\">오사카</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">오사카의 매력적인 문화와 일상에 빠져들 준비가 되셨나요? 오사카 하면 특히 음식! 음식을 빼놓을 수 없죠. 영국 가디언 지로부터 세계 최고의 음식 도시로 선정된 오사카! 오사카는 우리의 식욕을 만족시켜 줄 그 무언가를 가지고 있습니다. '먹을 수 없을 때까지 먹어라'는 오사카의 격언 쿠이다오레처럼, 이곳에는 그야말로 산해진미가 넘쳐납니다. 타코야키의 맛깔난 향기와 오코노미야키, 우동, 그리고 다른 일본 전통 음식들이 길가에 즐비합니다. 쇼핑 거리에서 쇼핑도 마음껏 즐기세요!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-4 col-sm-6 portfolio-item\">\r\n");
      out.write("        <div class=\"card h-100\">\r\n");
      out.write("            <a href=\"/travelduo/pdetail?num=tgbk\"><img class=\"card-img-top\" src=\"/travelduo/resources/images/bangkok.jpg\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"card-body\">\r\n");
      out.write("            <h4 class=\"card-title\">\r\n");
      out.write("              <a href=\"/travelduo/pdetail?num=tgbk\">방콕</a>\r\n");
      out.write("            </h4>\r\n");
      out.write("            <p class=\"card-text\">전통적 요소와 현대적 면모가 조화를 이룬 도시, 방콕\r\n");
      out.write("\r\n");
      out.write("동남아시아를 대표하는 열대의 도시 방콕은 최근 대대적인 재단장을 거쳐 한결 매력적인 모습을 자랑합니다. 다채로운 외국인 공동체, 나날이 발전하는 예술, 현대식 공항 덕분에 오늘날 방콕은 세계적인 트렌드에 한몫하고 있습니다. 나날이 변신을 거듭하고 있어 방콕을 자주 찾는 여행자조차 시시각각 변하는 이 도시의 모습에 놀라곤 합니다.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.row -->\r\n");
      out.write("    \r\n");
      out.write("  <br>\r\n");
      out.write("\r\n");
      out.write("    <!-- 매칭시스템 -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-lg-6\">\r\n");
      out.write("        <h2>매칭시스템</h2>\r\n");
      out.write("        <p>여행가 듀오를 이용해 여행 친구를 찾아보세요! </p>\r\n");
      out.write("        <ul> \r\n");
      out.write("          <li>여행가 듀오는 완벽한 여행 친구를 찾을 수 있는 최선의 방법입니다! 본 서비스는 여행 친구를 찾거나 동일한 여행 계획을 가진 싱글 여행 동반자들을 찾는 분들을 타겟으로 하고 있습니다. </li><br>\r\n");
      out.write("          <li>어디를 가시든지, 진심이 통하는 멋진 여행 친구를 만나보세요. 쇼핑도 하고 함께 놀러도 가고, 밥도 먹으며 바닷가와 이국적인 자연 경치를 감상하시거나 그냥 멋진 상대와 함께 편안한 휴식을 취해 보세요.</li><br>\r\n");
      out.write("          <li>꿈꾸던 곳을 방문하시고 그 곳에서 멋진 여행 친구를 찾아보세요. 여행 친구를 찾는 방법은 매우 안전하고, 편안하며 몇 초 밖에 소요되지 않습니다... 그리고 무엇보다도 즐겁구요!</li><br>\r\n");
      out.write("          <li><strong>듀오를 찾아 함께 여행해 보세요!</strong></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-lg-6\">\r\n");
      out.write("        <a href=\"index2.jsp\"><img class=\"img-fluid rounded\" src=\"./resources/images/home_match.jpg\" alt=\"\"></a> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /.row -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.container -->\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<!-- <link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.min.css\"> -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".floating { \r\n");
      out.write("background-color:#f9f9f9; \r\n");
      out.write("border:2px solid #000; \r\n");
      out.write("position: fixed; \r\n");
      out.write("left: 1%; \r\n");
      out.write("top: 180px; \r\n");
      out.write("margin-left: 20px; \r\n");
      out.write("text-align:center; \r\n");
      out.write("width:70px; \r\n");
      out.write("border-radius: 8px; \r\n");
      out.write("-webkit-border-radius: 8px; \r\n");
      out.write("z-index : 400;\r\n");
      out.write("} \r\n");
      out.write(".floating div:nth-child(1){\r\n");
      out.write(" border:2px solid; \r\n");
      out.write(" border-radius: 8px; \r\n");
      out.write(" } \r\n");
      out.write(" .floating div:nth-child(2){ \r\n");
      out.write(" border:2px solid; \r\n");
      out.write(" border-radius: 8px; \r\n");
      out.write(" }\r\n");
      out.write("  .floating div:nth-child(3){ \r\n");
      out.write("  border:2px solid; \r\n");
      out.write("  border-radius: 8px; \r\n");
      out.write("  }\r\n");
      out.write("  .floating div:nth-child(4){ \r\n");
      out.write("  border:2px solid; \r\n");
      out.write("  border-radius: 8px; \r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"floating\">\r\n");
      out.write(" <div><a href=\"https://open.kakao.com/o/sav6IQib\"><img src=\"/travelduo/resources/images/카카오톡.JPG\" width= \"60\" height= \"60\"></a></div>\r\n");
      out.write("  <div><a href=\"https://is.gd/travelduo\"><img src=\"/travelduo/resources/images/페이스북사진.png\" width= \"60\" height= \"60\"></a></div> \r\n");
      out.write("  <div><a href=\"https://www.instagram.com/traveldu0/\"><img src=\"/travelduo/resources/images/인스타그램사진.png\" width= \"60\" height= \"60\"></a></div> \r\n");
      out.write("  <div><a href=\"https://search.naver.com/search.naver?where=nexearch&sm=tab_jum&query=%EC%97%AC%ED%96%89%EA%B0%80%EB%93%80%EC%98%A4\"><img src=\"/travelduo/resources/images/네이버사진.png\" width= \"60\" height= \"60\"></a></div> \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Mobile Specific Meta -->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"img/fav.png\">\r\n");
      out.write("<!-- Author Meta -->\r\n");
      out.write("<meta name=\"author\" content=\"colorlib\">\r\n");
      out.write("<!-- Meta Description -->\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<!-- Meta Keyword -->\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<!-- meta character set -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- Site Title -->\r\n");
      out.write("<title>Travel Duo</title>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("\t\t\tCSS\r\n");
      out.write("\t\t\t============================================= -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/linearicons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/animate.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/fontawesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.linearicons.com/free/1.0.0/icon-font.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".carousel-item {\r\n");
      out.write("\theight: 100vh;\r\n");
      out.write("\tmin-height: 350px;\r\n");
      out.write("\tbackground: no-repeat center center scroll;\r\n");
      out.write("\t-webkit-background-size: cover;\r\n");
      out.write("\t-moz-background-size: cover;\r\n");
      out.write("\t-o-background-size: cover;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- start footer Area -->\r\n");
      out.write("\t\t\t\t<footer class=\"footer-area\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-7 col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"single-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>About Agency</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>copyright@kh.org 2019-03-04 master : 박건영<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttel : 02-1234-5678, 서울시 강남구 역삼동 777, fax : 02-1111-2356<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t본사 : 서울시 강남 역삼동 khacademy 1관 4층 S클래스<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t(주)자바스크류바투어 팀장 : 박건영<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t사업자등록번호 : 365-87-00612 | 관광사업등록증 : 제2019-000001호<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t개인정보 관리 책임자 : 조영선 부팀장 | TEL : 031-512-5293 | FAX : 02-754-6678<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t여행업자 전문인 배상책임보험 : 2018-2299298 / 보상 가입액 : 5억<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t일반 여행업의 기획 여행 : 100-000-2019 0002 9033 호/ 보증 보험 : 2억 \r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-5  col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"single-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><img src=\"/travelduo/resources/images/logoplus.png\" style=\"width:400px;height:230px;\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row footer-bottom d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"col-lg-8 col-sm-12 footer-text m-0\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved<i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t</div><br><br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!--\r\n");
      out.write("\t\tJS\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("\t<script type=\"text/javascript\"src=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"src=\"/travelduo/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/popper.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery-ui.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/easing.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/hoverIntent.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/superfish.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/main.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
