/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-03-31 19:24:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Mobile Specific Meta -->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"img/fav.png\">\r\n");
      out.write("<!-- Author Meta -->\r\n");
      out.write("<meta name=\"author\" content=\"colorlib\">\r\n");
      out.write("<!-- Meta Description -->\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<!-- Meta Keyword -->\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<!-- meta character set -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- Site Title -->\r\n");
      out.write("<title>Travel Duo</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction openNav() {\r\n");
      out.write("\t\tdocument.getElementById(\"mySidenav\").style.width = \"300px\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction closeNav() {\r\n");
      out.write("\t\tdocument.getElementById(\"mySidenav\").style.width = \"0\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.sidenav {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 0;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 3;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 0px;\r\n");
      out.write("  background-color: #111;\r\n");
      out.write("  overflow-x: hidden;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("  padding-top: 60px;\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav a {\r\n");
      out.write("  padding: 8px 8px 8px 32px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("  color: #818181;\r\n");
      out.write("  display: block;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav a:hover {\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav .closebtn {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50px;\r\n");
      out.write("  right: 0px;\r\n");
      out.write("  font-size: 36px;\r\n");
      out.write("  margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#main {\r\n");
      out.write("  transition: margin-right .5s;\r\n");
      out.write("  padding: 16\tpx;\r\n");
      out.write("  text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" @media screen and (max-height: 6000px) {\r\n");
      out.write("  .sidenav {padding-top: 15px;}\r\n");
      out.write("  .sidenav a {font-size: 18px;}\r\n");
      out.write("}\r\n");
      out.write("/* \r\n");
      out.write("header nav ul { list-style: none; } \r\n");
      out.write(" */\r\n");
      out.write("/* header nav ul li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tbackground-color:rgba(255,255,255,0.0);\r\n");
      out.write("\ttext-decoration: none; */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("/* header nav ul li a {\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-top: 15px;\r\n");
      out.write("\tpadding-bottom: 0;\r\n");
      out.write("\twidth: 158px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 25px;\r\n");
      out.write("\ttext-decoration:none; */\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* header nav ul li a:hover {\r\n");
      out.write("/* \tbackground: gray;\r\n");
      out.write("\ttext-shadow: 1px 1px 2px white;\r\n");
      out.write("\tbox-shadow: 2px 2px 4px white; */\r\n");
      out.write("\t\r\n");
      out.write("} */\r\n");
      out.write("#h1 {\r\n");
      out.write("/* background-image: url(\"/travelduo/resources/images/여행가듀오_로고_투명.png\"); */\r\n");
      out.write("/* \tbackground-color:rgba(255,255,255,0.5); */\r\n");
      out.write("width: 200px;\r\n");
      out.write("height: 80px;\r\n");
      out.write("/* background-repeat: no-repeat; */\r\n");
      out.write("float: left;\r\n");
      out.write("}\r\n");
      out.write("/* #h2 {\r\n");
      out.write("width: 3000px;\r\n");
      out.write("height: 80px;\r\n");
      out.write("} */\r\n");
      out.write("/* #three{\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-top: 0px;\r\n");
      out.write("\tpadding-bottom: 0;\r\n");
      out.write("\twidth: 70px;\r\n");
      out.write("\theight: 60px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tfont-size: 45px;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("}\r\n");
      out.write(" */\r\n");
      out.write(".three{\r\n");
      out.write("width: 150px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col {\r\n");
      out.write("    display: block;\r\n");
      out.write("    float: right;\r\n");
      out.write("    margin: 1% 0 1% 1.6%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col:first-of-type {\r\n");
      out.write("    margin-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".row .three {\r\n");
      out.write("padding: 1px 3px;\r\n");
      out.write("    -webkit-box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    background-color: #2c3e50;\r\n");
      out.write("    color: #ecf0f1;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hamburger .line {\r\n");
      out.write("    width: 10px;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    background-color: #ecf0f1;\r\n");
      out.write("    display: block;\r\n");
      out.write("    margin: 2px auto;\r\n");
      out.write("    -webkit-transition: all 0.3s ease-in-out;\r\n");
      out.write("    -o-transition: all 0.3s ease-in-out;\r\n");
      out.write("    transition: all 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hamburger:hover {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hamburger-4.is-active .line:nth-child(1),\r\n");
      out.write("#hamburger-4.is-active .line:nth-child(3) {\r\n");
      out.write("    width: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hamburger-4.is-active .line:nth-child(1) {\r\n");
      out.write("    -webkit-transform: translateX(10px) rotate(45deg);\r\n");
      out.write("    -ms-transform: translateX(10px) rotate(45deg);\r\n");
      out.write("    -o-transform: translateX(10px) rotate(45deg);\r\n");
      out.write("    transform: translateX(10px) rotate(45deg);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hamburger-4.is-active .line:nth-child(3) {\r\n");
      out.write("    -webkit-transform: translateX(10px) rotate(-45deg);\r\n");
      out.write("    -ms-transform: translateX(10px) rotate(-45deg);\r\n");
      out.write("    -o-transform: translateX(10px) rotate(-45deg);\r\n");
      out.write("    transform: translateX(10px) rotate(-45deg);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("\t\t\tCSS\r\n");
      out.write("\t\t\t============================================= -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/linearicons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/travelduo/resources/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/animate.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".listText {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".listText:hover {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"container main-menu\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-center justify-content-between d-flex\">\r\n");
      out.write("\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/travelduo/index.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/travelduo/resources/images/logo2.png\" alt=\"\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"height: 30px;\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<nav id=\"nav-menu-container\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.html\">매칭시스템</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/views/product/productListView.jsp\">국내여행</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/views/product/productListView.jsp\">해외여행\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-angle-down\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-home.html\">호주</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/views/product/productListView.jsp\">일본</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">독일</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">러시아</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">스위스</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">중국</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">멕시코</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"blog-single.html\">괌</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"hotels.html\">테마여행</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"insurance.html\">패키지여행</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"/travelduo/views/admin/dashBoard.jsp\">여행후기</a>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"elements.html\">Elements</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"\"><a href=\"\">Level 2 </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Item One</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Item Two</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span style=\"font-size:15px;color:white;cursor:pointer\" onclick=\"openNav()\">&#9776;　</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- #nav-menu-container -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"mySidenav\" class=\"sidenav\">\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\r\n");
      out.write("  <a href=\"/travelduo\"><img src=\"/travelduo/resources/images/logo2.png\" width= \"150\" height=\"54\"></a><br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("<!--   로그인화면 -->\r\n");
      out.write("<!--   <form>\r\n");
      out.write("                <div class=\"form-label-group\">\r\n");
      out.write("                  <input type=\"id\" id=\"inputId\" class=\"form-control\" placeholder=\"ID\" required autofocus>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-label-group\">\r\n");
      out.write("                  <input type=\"password\" id=\"inputPassword\" class=\"form-control\" placeholder=\"Password\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <button class=\"btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2\" type=\"submit\">로그인</button>\r\n");
      out.write("                \r\n");
      out.write("                <button class=\"btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2\" type=\"button\">아이디 비밀번호찾기</button>\r\n");
      out.write("                <button class=\"btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2\" type=\"button\">회원가입</button>\r\n");
      out.write("              </form> -->\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("<!-- 회원가입 -->\r\n");
      out.write("<!--               <article class=\"container\">\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("                <div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("                <h3><a href=\"#\">회원가입</a></h3>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-6 col-md-offset-3\">\r\n");
      out.write("                <form role=\"form\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputName\"><a href=\"#\">성명</a></label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"inputName\" placeholder=\"이름을 입력해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"InputEmail\"><a href=\"#\">이메일 주소</a></label>\r\n");
      out.write("                        <input type=\"email\" class=\"form-control\" id=\"InputEmail\" placeholder=\"이메일 주소를 입력해주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputPassword\"><a href=\"#\">비밀번호</a></label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"inputPassword\" placeholder=\"비밀번호를 입력해주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputPasswordCheck\"><a href=\"#\">비밀번호 확인</a></label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"inputPasswordCheck\" placeholder=\"비밀번호 확인을 위해 다시한번 입력 해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputMobile\"><a href=\"#\">휴대폰 번호</a></label>\r\n");
      out.write("                        <input type=\"tel\" class=\"form-control\" id=\"inputMobile\" placeholder=\"휴대폰번호를 입력해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputtelNO\"><a href=\"#\">비밀번호 힌트</a></label>\r\n");
      out.write("                        <select name=\"\">\r\n");
      out.write("                        <option value=\"좋아하는 색은?\" selected>좋아하는 색은?\r\n");
      out.write("                        <option value=\"아버지 성함은?\">아버지 성함은?\r\n");
      out.write("                        <option value=\"어머니 성함은?\">어머니 성함은?\r\n");
      out.write("                        <option value=\"첫번째 연인의 이름은?\">첫사랑 했던 연인의 이름은?\r\n");
      out.write("                        <option value=\"일생중 일어났던 중요한 사건은?\">일생중 일어났던 중요한 사건은?\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"hint\"><a href=\"#\">힌트의 정답</a></label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"inputHint\" placeholder=\"정답을 입력해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                    <label>약관 동의</label>\r\n");
      out.write("                    <div data-toggle=\"buttons\">\r\n");
      out.write("                    <label class=\"btn btn-primary active\">\r\n");
      out.write("                    <span class=\"fa fa-check\"></span>\r\n");
      out.write("                    <input id=\"agree\" type=\"checkbox\" autocomplete=\"off\" checked>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <a href=\"#\">이용약관</a>에 동의합니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <div class=\"form-group text-center\">\r\n");
      out.write("                        <button type=\"submit\" id=\"join-submit\" class=\"btn btn-primary\">\r\n");
      out.write("                            회원가입<i class=\"fa fa-check spaceLeft\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-warning\">\r\n");
      out.write("                            가입취소<i class=\"fa fa-times spaceLeft\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("\r\n");
      out.write("        </article> -->\r\n");
      out.write("        \r\n");
      out.write("<!-- 마이페이지 -->\r\n");
      out.write(" <ul class=\"fa-ul\">\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>회원정보 확인/수정</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>찜한 상품</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>결제 내역 확인</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>고객센터</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>로그아웃</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\t<!-- #header -->\r\n");
      out.write("\t<!--\r\n");
      out.write("\t\tJS\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("\t\t\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/js2/popper.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/js2/jquery-ui.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/js2/easing.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/js2/hoverIntent.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/js2/superfish.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/js2/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/js2/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/js2/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/js2/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"/travelduo/resources/js/js2/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
