/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2019-04-05 07:28:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.faq;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class faq_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/faq/../common/footer.jsp", Long.valueOf(1554293034000L));
    _jspx_dependants.put("/views/faq/../common/header.jsp", Long.valueOf(1554445428093L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");

	Member loginUser = (Member)session.getAttribute("loginUser");

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>travelduo</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/main.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function openNav() {\r\n");
      out.write("\t  document.getElementById(\"mySidenav\").style.width = \"257px\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction closeNav() {\r\n");
      out.write("\t  document.getElementById(\"mySidenav\").style.width = \"0\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".sidenav {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  width: 0;\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  z-index: 1;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 0;\r\n");
      out.write("  background-color: #111;\r\n");
      out.write("  overflow-x: hidden;\r\n");
      out.write("  transition: 0.5s;\r\n");
      out.write("  padding-top: 60px;\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" /* 회원가입 , ID/PW 찾기 */\r\n");
      out.write(".sidenav a {\r\n");
      out.write("  padding: 8px 8px 8px 9px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 25px;\r\n");
      out.write("  color: #818181;\r\n");
      out.write("  display: block;\r\n");
      out.write("  transition: 0.3s;\r\n");
      out.write("  float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav a:hover {\r\n");
      out.write("  color: #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidenav .closebtn {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  right: 23px;\r\n");
      out.write("  font-size: 36px;\r\n");
      out.write("  margin-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-height: 6000px) {\r\n");
      out.write("  .sidenav {padding-top: 15xp;}\r\n");
      out.write("  .sidenav a {font-size: 18px;}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 여행가듀오 로고아래 로그인에 대한 글씨 */\r\n");
      out.write(" .logincolor818181 { \r\n");
      out.write(" color: #818181;\r\n");
      out.write(" } \r\n");
      out.write(" \r\n");
      out.write("/*로그인 글자 앞에 생기는 줄에대한 것  */\r\n");
      out.write(".logincolor818181:after {display: inline-block; margin: 0 0 6px 5px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:\r\n");
      out.write("44%; }\r\n");
      out.write("\r\n");
      out.write("/*로그인버튼  앞에 생기는 줄에 대한 것  */\r\n");
      out.write(".line:before {display: inline-block; margin: 0 5px 6px 23px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:\r\n");
      out.write("38%; }\r\n");
      out.write("\r\n");
      out.write("/*로그인 후 햄버거 클릭 시 나오는 앞선에 대한 것  */\r\n");
      out.write(".line2:before {display: inline-block; margin: 0 5px 6px 23px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:83%;}\r\n");
      out.write("\r\n");
      out.write("/*로그인 후 햄버거 클릭 시 나오는 뒷선에 대한 것  */\r\n");
      out.write(".line3:before {display: inline-block; margin: 0 5px 6px 23px; height: 1px; content: \" \"; text-shadow: none; background-color: #999; width:\r\n");
      out.write("83%;}\r\n");
      out.write("\r\n");
      out.write("/* \r\n");
      out.write("\t\t\tCSS\r\n");
      out.write("\t\t\t============================================= -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/linearicons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"/travelduo/resources/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/animate.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.min.css\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"main\">\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"container main-menu\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-center justify-content-between d-flex\">\r\n");
      out.write("\t\t\t\t<div id=\"logo\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/travelduo/index.jsp\"><img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"/travelduo/resources/images/logo2.png\" alt=\"\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"height: 30px;\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<nav id=\"nav-menu-container\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/index2.jsp\">매칭시스템</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pialist\">국내여행</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/poalist\">해외여행\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=일본\">일본</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=영국\">영국</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=프랑스\">프랑스</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=체코\">체코</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=미국\">미국</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=이탈리아\">이탈리아</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=헝가리\">헝가리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=독일\">독일</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=중국\">중국</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=호주\">호주</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/pclist?coun=태국\">태국</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/travelduo/blist\">매칭게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 if(loginUser!=null) { 
      out.write("\r\n");
      out.write("\t\t<li><a href=\"/travelduo/matchList?userid=");
      out.print( loginUser.getUserId() );
      out.write("\"> 내게 온 매칭</a></li>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 }else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li class=\"menu-has-children\"><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/nlist?page=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/views/faq/faq.jsp\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"/travelduo/qlist?page=1\">QnA</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a><span style=\"font-size:15px;color:white;cursor:pointer\" onclick=\"openNav()\">&#9776;　</span>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- #nav-menu-container -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"mySidenav\" class=\"sidenav\">\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("  <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\r\n");
      out.write("  <a href=\"/travelduo\" align=\"center\"><img src=\"/travelduo/resources/images/logo2.png\" width= \"180\" height= \"60\"></a><br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("  <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
if(loginUser!=null){ 
      out.write("<!--로그인하였을 경우  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<p class=\"line2\"></p>\r\n");
      out.write("<ul class=\"fa-ul\">\r\n");
      out.write("\r\n");
      out.write("<a href=\"/travelduo/views/member/memberMyPage.jsp\" > <img src=\"/travelduo/resources/images/Person_icon-icons.com_51960.png\" width= \"20\" height= \"20\"> 회원정보 보기/수정</a>\r\n");
      out.write("<a href=\"/travelduo/index2.jsp\" > <img src=\"/travelduo/resources/images/멤버 매칭시스템 로고.png\" width= \"20\" height= \"20\"> 매칭 시스템</a>\r\n");
      out.write("<a href=\"/travelduo/nlist?page=1\" > <img src=\"/travelduo/resources/images/Phone-call_icon-icons.com_51956.png\" width= \"20\" height= \"20\"> 고객 센터 문의</a>\r\n");
      out.write("<a href=\"/travelduo/logout\" > <img src=\"/travelduo/resources/images/Login_icon-icons.com_52028 (1).png\" width= \"20\" height= \"20\"> 로그아웃</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("<p class=\"line3\"></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t<!-- \t <ul class=\"fa-ul\">\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span><a href=\"\"><h5>회원정보 확인/수정</h5></a></li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>찜한 상품</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>결제 내역 확인</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span>고객센터</li>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("              <a href=\"/travelduo/logout\"><li class=\"text-muted\"><span class=\"fa-li\"><i class=\"fas fa-times\"></i></span></li>로그아웃</a>\r\n");
      out.write("              <br>\r\n");
      out.write("              <br>\r\n");
      out.write("           </ul>  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
}else{ 
      out.write("<!--로그인하지 않았을 경우  -->\r\n");
      out.write("<form action=\"/travelduo/mlogin\" method=\"post\">\r\n");
      out.write(" \r\n");
      out.write("  <h4 class=\"logincolor818181\">&ensp;&ensp; 로그인</h4> \r\n");
      out.write("\r\n");
      out.write("<div style = \"padding: 4px 1px 3px 3px;\">  \r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>&ensp;&emsp;<input type=\"text\" name=\"userid\" placeholder=\"ID\" required></td>\r\n");
      out.write("\t</tr><br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style = \"padding: 4px 1px 10px 3px;\"> \r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>&ensp;&emsp;<input type=\"password\" name=\"userpwd\" placeholder=\"Password\" required></td><br>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<tr>\r\n");
      out.write("&ensp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp;&ensp;&ensp;&ensp;<p class=\"line\"><input class=btn type=\"submit\" value=\"로 그 인\"></p>\r\n");
      out.write("</tr>\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<div class=\"btn\">\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"/travelduo/views/member/memberAccept.jsp\">회원가입</a>\r\n");
      out.write("\t<a href=\"/travelduo/views/member/memberFindId.jsp\">ID/PW 찾기</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</tr>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 if(loginUser != null && loginUser.getUserId().equals("admin")){ 
      out.write("\r\n");
      out.write("\t<!--관리자 전용 페이지 만든후 거기로이동하게 끔  --> \t\r\n");
      out.write("\t<ul class=\"fa-ul\">\r\n");
      out.write("\t<a href=\"/travelduo/mm\">관리자 페이지로 이동</a>\r\n");
      out.write("\t</ul>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--   로그인화면 -->\r\n");
      out.write("<!--   <form>\r\n");
      out.write("                <div class=\"form-label-group\">\r\n");
      out.write("                  <input type=\"id\" id=\"inputId\" class=\"form-control\" placeholder=\"ID\" required autofocus>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-label-group\">\r\n");
      out.write("                  <input type=\"password\" id=\"inputPassword\" class=\"form-control\" placeholder=\"Password\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                <button class=\"btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2\" type=\"submit\">로그인</button>\r\n");
      out.write("                \r\n");
      out.write("                <button class=\"btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2\" type=\"button\">아이디 비밀번호찾기</button>\r\n");
      out.write("                <button class=\"btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2\" type=\"button\">회원가입</button>\r\n");
      out.write("              </form> -->\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("<!-- 회원가입 -->\r\n");
      out.write("<!--               <article class=\"container\">\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("                <div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("                <h3><a href=\"#\">회원가입</a></h3>\r\n");
      out.write("                <br><br>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-sm-6 col-md-offset-3\">\r\n");
      out.write("                <form role=\"form\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputName\"><a href=\"#\">성명</a></label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"inputName\" placeholder=\"이름을 입력해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"InputEmail\"><a href=\"#\">이메일 주소</a></label>\r\n");
      out.write("                        <input type=\"email\" class=\"form-control\" id=\"InputEmail\" placeholder=\"이메일 주소를 입력해주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputPassword\"><a href=\"#\">비밀번호</a></label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"inputPassword\" placeholder=\"비밀번호를 입력해주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputPasswordCheck\"><a href=\"#\">비밀번호 확인</a></label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"inputPasswordCheck\" placeholder=\"비밀번호 확인을 위해 다시한번 입력 해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputMobile\"><a href=\"#\">휴대폰 번호</a></label>\r\n");
      out.write("                        <input type=\"tel\" class=\"form-control\" id=\"inputMobile\" placeholder=\"휴대폰번호를 입력해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"inputtelNO\"><a href=\"#\">비밀번호 힌트</a></label>\r\n");
      out.write("                        <select name=\"\">\r\n");
      out.write("                        <option value=\"좋아하는 색은?\" selected>좋아하는 색은?\r\n");
      out.write("                        <option value=\"아버지 성함은?\">아버지 성함은?\r\n");
      out.write("                        <option value=\"어머니 성함은?\">어머니 성함은?\r\n");
      out.write("                        <option value=\"첫번째 연인의 이름은?\">첫사랑 했던 연인의 이름은?\r\n");
      out.write("                        <option value=\"일생중 일어났던 중요한 사건은?\">일생중 일어났던 중요한 사건은?\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"hint\"><a href=\"#\">힌트의 정답</a></label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"inputHint\" placeholder=\"정답을 입력해 주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                    <label>약관 동의</label>\r\n");
      out.write("                    <div data-toggle=\"buttons\">\r\n");
      out.write("                    <label class=\"btn btn-primary active\">\r\n");
      out.write("                    <span class=\"fa fa-check\"></span>\r\n");
      out.write("                    <input id=\"agree\" type=\"checkbox\" autocomplete=\"off\" checked>\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <a href=\"#\">이용약관</a>에 동의합니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <div class=\"form-group text-center\">\r\n");
      out.write("                        <button type=\"submit\" id=\"join-submit\" class=\"btn btn-primary\">\r\n");
      out.write("                            회원가입<i class=\"fa fa-check spaceLeft\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-warning\">\r\n");
      out.write("                            가입취소<i class=\"fa fa-times spaceLeft\"></i>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    <br>text-muted\r\n");
      out.write("                    <br>\r\n");
      out.write("\r\n");
      out.write("        </article> -->\r\n");
      out.write("        <br><br>\r\n");
      out.write("<!-- 마이페이지 -->\r\n");
      out.write("<!-- #header -->\r\n");
      out.write("\t<!--\r\n");
      out.write("\t\tJS\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("\t\t\t   <script type=\"text/javascript\" src=\"/travelduo/resources/js/superfish.min.js\"></script>\r\n");
      out.write("   <script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("   <script type=\"text/javascript\" src=\"/travelduo/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("   <script type=\"text/javascript\" src=\"/travelduo/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr style=\"clear:left;\"> \r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row faq_margin\">\r\n");
      out.write("<h2>자주하는 질문(FAQ)</h2>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("\t<div class=\"accordion\" id=\"accordionExample\">\r\n");
      out.write("\t<div class=\"col-md-15 col-md-offset-1\">\r\n");
      out.write("  <div class=\"card\">\r\n");
      out.write("    <div class=\"card-header\" id=\"headingOne\">\r\n");
      out.write("      <h2 class=\"mb-0\">\r\n");
      out.write("        <button class=\"btn btn-link\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\">\r\n");
      out.write("          해외여행자 보험이란??\r\n");
      out.write("        </button>\r\n");
      out.write("      </h2>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"collapseOne\" class=\"collapse show\" aria-labelledby=\"headingOne\" data-parent=\"#accordionExample\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("       여행도중에 우연히 발생하게 되는 각종 사고 및 질병, 조난 시 구조비용, 휴대품의 도난 손해 등의 보상을 목적으로 하는 보험. \r\n");
      out.write("\r\n");
      out.write("해외여행자보험의 실손의료비는 여러 보험사에 중복 계약을 했더라도 중복보상이 안되고 비례보상으로 처리된다. \r\n");
      out.write("(단 , 사망보험금은 중복보상 가능) \r\n");
      out.write("( 휴대품 손해, 배상책임도 비례보상으로 처리) \r\n");
      out.write("국내에서 상해 및 질병으로 치료 받는경우 발생한 실손의료비에 대해 100% 보상을 받을수 없다. 자기부담금이 설정되어 있어 그만큼의 비용을 제외하고 보상을 받을수 있다. \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"card\">\r\n");
      out.write("    <div class=\"card-header\" id=\"headingTwo\">\r\n");
      out.write("      <h2 class=\"mb-0\">\r\n");
      out.write("        <button class=\"btn btn-link collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n");
      out.write("          항공권 업그레이드 가능한가요?\r\n");
      out.write("        </button>\r\n");
      out.write("      </h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionExample\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        보통 패키지 상품의 경우는 기본 이코노미 좌석을 이용합니다. \r\n");
      out.write("비지니즈석이나 그 이상으로 업그레이드 하실 경우는, 차액부분을 부담하시거나 또는 고객님의 해당항공사 마일리지를 이용하셔서도 가능하십니다. \r\n");
      out.write("\r\n");
      out.write("단, 성수기 날짜나 좌석확보가 어려운 날짜는 불가할 수도 있으니 사전에 문의하시어 예약하시는것이 중요합니다.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"card\">\r\n");
      out.write("    <div class=\"card-header\" id=\"headingThree\">\r\n");
      out.write("      <h2 class=\"mb-0\">\r\n");
      out.write("        <button class=\"btn btn-link collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("          돌아오는 날짜 변경 가능한가요?\r\n");
      out.write("        </button>\r\n");
      out.write("      </h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"collapseThree\" class=\"collapse\" aria-labelledby=\"headingThree\" data-parent=\"#accordionExample\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        일정이 모두 끝난 후 개별귀국을 원하실 경우는 출발전에 우선 돌아오실 날짜와 좌석가능여부를 사전에 체크.예약과 발권을 완료 하셔야하며 한국에서 혹은 현지에서 돌아오실때 일정금액을 현지공항에서 지불하셔야 하시면 됩니다. \r\n");
      out.write("노선에 따라서 또는 항공편에 따라서 리턴변경이 불가한 경우도 있으니, 출발전에 필히 가능여부를 체크하시는 것이 중요합니다.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"card\">\r\n");
      out.write("    <div class=\"card-header\" id=\"headingFour\">\r\n");
      out.write("      <h2 class=\"mb-0\">\r\n");
      out.write("        <button class=\"btn btn-link collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseFour\" aria-expanded=\"false\" aria-controls=\"collapseFour\">\r\n");
      out.write("          E-Ticket이란?\r\n");
      out.write("        </button>\r\n");
      out.write("      </h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"collapseFour\" class=\"collapse\" aria-labelledby=\"headingFour\" data-parent=\"#accordionExample\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        기존 종이항공권(Paper Ticket)대신 전자항공권(Electronic Ticket)으로 발급하여 \r\n");
      out.write("고객님의 모든 여행정보가 항공사의 시스템에 보관/처리되는 서비스입니다. \r\n");
      out.write("\r\n");
      out.write("고객님의 티켓정보가 항공사의 시스템에 전자문서로 보관 되므로 분실의 위험이 없으며 원하시는 e-mail 또는 fax로도 받아보실 수 있습니다. \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"card\">\r\n");
      out.write("    <div class=\"card-header\" id=\"headingFive\">\r\n");
      out.write("      <h2 class=\"mb-0\">\r\n");
      out.write("        <button class=\"btn btn-link collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseFive\" aria-expanded=\"false\" aria-controls=\"collapseFive\">\r\n");
      out.write("          면세점에서 구입한도와 입국시 면세한도는 얼마인가요?\r\n");
      out.write("        </button>\r\n");
      out.write("      </h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"collapseFive\" class=\"collapse\" aria-labelledby=\"headingFive\" data-parent=\"#accordionExample\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        여행자 1인당 총 면세품 구입금액이 $3,000을 넘어서는 안되며, 시계 등의 고가품은 \r\n");
      out.write("물건 1개당 $400을 넘어서는 안됩니다.\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$3,000을 초과하여 물품을 반입하는 경우, 비록 출국시 국내 면세점에서 구입한 \r\n");
      out.write("물품일지라도 세관에 반드시 신고하여 관세를 납부하여야 합니다. 위 사항을 위반할 \r\n");
      out.write("시에는 관세법 규정에 의거 처벌받게 됩니다.\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("우리나라 입국 시에는 면세금액 한도가 $400미만으로 적용되기 때문에 주의해서 \r\n");
      out.write("들어오셔야합니다.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"card\">\r\n");
      out.write("    <div class=\"card-header\" id=\"headingSix\">\r\n");
      out.write("      <h2 class=\"mb-0\">\r\n");
      out.write("        <button class=\"btn btn-link collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseSix\" aria-expanded=\"false\" aria-controls=\"collapseSix\">\r\n");
      out.write("         애완동물을 기내에 데려갈 수 있나요?\r\n");
      out.write("        </button>\r\n");
      out.write("      </h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"collapseSix\" class=\"collapse\" aria-labelledby=\"headingSix\" data-parent=\"#accordionExample\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("       가능합니다. 하지만 탑승할 수 있는 애완 동물의 종류가 제한이 되어있습니다. \r\n");
      out.write("보통 1인 1마리로 제한, 예방 접종과 건강 진단서 등 서류를 준비하셔야합니다. 애완동물의 종류나 입국하는 나라에 따라서 데려갈 수 없는 경우도 있으니 자세한 사항은 해당 항공사로 문의하시면 됩니다. \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"card\">\r\n");
      out.write("    <div class=\"card-header\" id=\"headingSeven\">\r\n");
      out.write("      <h2 class=\"mb-0\">\r\n");
      out.write("        <button class=\"btn btn-link collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseSeven\" aria-expanded=\"false\" aria-controls=\"collapseSeven\">\r\n");
      out.write("          도둑 맞았을 때는 어떻게 대처 해야하나요?\r\n");
      out.write("        </button>\r\n");
      out.write("      </h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"collapseSeven\" class=\"collapse\" aria-labelledby=\"headingSeven\" data-parent=\"#accordionExample\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("        1)절도를 당한 즉시 가장 가까운 경찰서로 가서 반드시 POLICE REPORT를 받습니다. 이때 신고는 본인이 직접 작성해야 하며 절도를 당한 여행객 인원수대로 별도작성해야 손해를 줄일 가능성이 더 있습니다. \r\n");
      out.write("2)본국으로 귀국후 POLICE REPORT를 가지고 보험회사에 신고합니다. \r\n");
      out.write("보험사 제출시 필요서류 : POLICE REPORT, 손상품 수리견적서(영수증 포함),여권사본, 통장사본 (본인의 통장이 아닐 경우 관계를 나타낼 수 있는 서류) \r\n");
      out.write("\r\n");
      out.write("보험처리가 안되는 것들 : 현금, 수표, 항공권 등등의 유가증권 \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("   <div class=\"card\">\r\n");
      out.write("    <div class=\"card-header\" id=\"headingeight\">\r\n");
      out.write("      <h2 class=\"mb-0\">\r\n");
      out.write("        <button class=\"btn btn-link collapsed\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapseeight\" aria-expanded=\"false\" aria-controls=\"collapseeight\">\r\n");
      out.write("          팁은 어떻게 주어야 하나요?\r\n");
      out.write("        </button>\r\n");
      out.write("      </h2>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"collapseeight\" class=\"collapse\" aria-labelledby=\"headingeight\" data-parent=\"#accordionExample\">\r\n");
      out.write("      <div class=\"card-body\">\r\n");
      out.write("       - 유럽이나 미주 지역에서는 식당에서도 10% 정도의 팁을 주는 게 예의랍니다. \r\n");
      out.write("\r\n");
      out.write("- 가방을 방까지 들어다주거나 호텔에서 서비스를 받았다면 조금의 팁을 주는게 관례입니다.($1 정도) \r\n");
      out.write("\r\n");
      out.write("- 방을 청소해주거나 CHECK-OUT할 때 침대옆 탁자위에 $1 정도 놓는 것이 예의랍니다.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Mobile Specific Meta -->\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<!-- Favicon-->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"img/fav.png\">\r\n");
      out.write("<!-- Author Meta -->\r\n");
      out.write("<meta name=\"author\" content=\"colorlib\">\r\n");
      out.write("<!-- Meta Description -->\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<!-- Meta Keyword -->\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<!-- meta character set -->\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- Site Title -->\r\n");
      out.write("<title>Travel Duo</title>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("\t\t\tCSS\r\n");
      out.write("\t\t\t============================================= -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/linearicons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/magnific-popup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/jquery-ui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/nice-select.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/animate.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/main.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/travelduo/resources/css/fontawesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.linearicons.com/free/1.0.0/icon-font.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".carousel-item {\r\n");
      out.write("\theight: 100vh;\r\n");
      out.write("\tmin-height: 350px;\r\n");
      out.write("\tbackground: no-repeat center center scroll;\r\n");
      out.write("\t-webkit-background-size: cover;\r\n");
      out.write("\t-moz-background-size: cover;\r\n");
      out.write("\t-o-background-size: cover;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- start footer Area -->\r\n");
      out.write("\t\t\t\t<footer class=\"footer-area\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-7 col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"single-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h6>About Agency</h6>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>copyright@kh.org 2019-03-04 master : 박건영<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttel : 02-1234-5678, 서울시 강남구 역삼동 777, fax : 02-1111-2356<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t본사 : 서울시 강남 역삼동 khacademy 1관 4층 S클래스<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t(주)자바스크류바투어 팀장 : 박건영<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t사업자등록번호 : 365-87-00612 | 관광사업등록증 : 제2019-000001호<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t개인정보 관리 책임자 : 조영선 부팀장 | TEL : 031-512-5293 | FAX : 02-754-6678<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t여행업자 전문인 배상책임보험 : 2018-2299298 / 보상 가입액 : 5억<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t일반 여행업의 기획 여행 : 100-000-2019 0002 9033 호/ 보증 보험 : 2억 \r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-5  col-md-6 col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"single-footer-widget\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><img src=\"/travelduo/resources/images/logoplus.png\" style=\"width:400px;height:230px;\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"row footer-bottom d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"col-lg-8 col-sm-12 footer-text m-0\"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->\r\n");
      out.write("Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved<i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t</div><br><br>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<!--\r\n");
      out.write("\t\tJS\r\n");
      out.write("\t\t============================================= -->\r\n");
      out.write("\t<script type=\"text/javascript\"src=\"/travelduo/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"src=\"/travelduo/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/popper.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery-ui.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/easing.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/hoverIntent.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/superfish.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/jquery.nice-select.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/travelduo/resources/js/main.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<style>\r\n");
      out.write(".faq_margin{\r\n");
      out.write("\r\n");
      out.write("\tmargin-left:430px;\r\n");
      out.write("\tmargin-top:100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
